# .github/workflows/scrape_and_upload.yml
name: Scrape Shwapno 

on:
  schedule:
    # প্রতিদিন রাত ১২:০০ টায় (UTC) রান হবে।
    # UTC থেকে বাংলাদেশের সময় (BST/BDT) ৬ ঘণ্টা এগিয়ে।
    # তাই, এটি বাংলাদেশের সময় সকাল ৬টায় রান হবে।
    # আপনি আপনার পছন্দ মতো সময় সেট করতে পারেন।
    - cron: '0 0 * * *'
  workflow_dispatch: # হাতে ম্যানুয়ালি রান করার জন্য

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # আপনার পছন্দসই পাইথন সংস্করণ

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 gspread oauth2client

    - name: Run scraper
      env:
        # আপনার Google Service Account Key JSON স্ট্রিংটি এখানে এনকোড করা হবে।
        # এই ভেরিয়েবলটি গিটহাব সিক্রেটস থেকে লোড হবে।
        GSPREAD_SERVICE_ACCOUNT_KEY: ${{ secrets.GSPREAD_SERVICE_ACCOUNT_KEY }}
      run: |
        python shwapno_scraper.py
